//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarServicesCarParts
    {
        public int ID { get; set; }
        public int CarServiceID { get; set; }
        public int CarPartID { get; set; }
        public int QuantityOfPart { get; set; }
    
        public virtual CarParts CarParts { get; set; }
        public virtual CarServices CarServices { get; set; }
    }
}
