//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NagievShop2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemOrder
    {
        public int ID { get; set; }
        public int ItemID { get; set; }
        public int OrderID { get; set; }
        public int Quantity { get; set; }
        public decimal Purchase { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Order Order { get; set; }
    }
}
